#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

p_check(){
if ! pgrep -a tor >/dev/null 2>&1 || ! ss -tulpn | grep -IE "6969|9150|9151" >/dev/null 2>&1; then
      archnon restart >/dev/null 2>&1     
fi
}

while true; do
   p_check >/dev/null 2>&1
done & >/dev/null 2>&1


