#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"

# Dependencies && pkg managers

if ! (command -v nc >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v nft >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1); then

       if [[ $(command -v apt) ]]; then

           pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo )

           if ! apt install "${pkgs[@]}" -y; then
	          echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	          exit 1
	       fi
	       wait

        elif [[ $(command -v pacman) ]]; then

              pkgs=( openbsd-netcat curl tor nftables procps-ng networkmanager iproute2 coreutils util-linux bash sudo )

              if ! pacman -Syy "${pkgs[@]}" --needed --noconfirm --overwrite "*"; then
  		        echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	            exit 1
	         fi
	         wait

        elif [[ $(command -v dnf) ]]; then

              pkgs=( epel-release nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo )

              if ! dnf -y install --allowerasing "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v yum) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo )

              if ! yum -y install "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v zypper) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo )

              if ! zypper install "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v apk) ]]; then

              pkgs=( netcat-openbsd curl tor nftables procps networkmanager iproute2 coreutils util-linux bash sudo )

              if ! apk add --no-cache "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v xbps-install) ]]; then

              pkgs=( openbsd-netcat curl tor iproute2 coreutils util-linux bash nftables sudo procps-ng NetworkManager )

              if ! xbps-install -Sy -f -y -o "*" "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	             exit 1
	          fi
	          wait
	elif [[ $(command -v emerge) ]]; then
	
	      pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo )
	
	      if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
		    echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW}) !!${NC}"
	            exit 1
	      fi
	      wait
        else
	      pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo )
              echo -e "${RED}[${GREEN}err${RED}]${BLUE} Missing dependencies !!${NC}"
	      echo -e "${RED}[${GREEN}err${RED}]${GREEN} Bad usage: unsuported pkg manager, please, install: ${BLUE}(${YELLOW}${pkgs[@]}${BLUE})${NC}"
              exit 1
        fi
fi

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/archnon.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/archnon.service
    cat << 'EOT' > /etc/systemd/system/archnon.service
[Unit]
Description=ArchNoN Custom Service Here !!
[Service]
Type=forking
ExecStart=/usr/bin/archnon start
RemainAfterExit=yes
User=root
[Install]
WantedBy=multi-user.target
EOT

fi

if [ ! -f /etc/sv/archnon/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/archnon/
    touch /etc/sv/archnon/run
    cat << 'EOT' > /etc/sv/archnon/run
#!/bin/sh
exec archnon start
EOT
    chmod +x /etc/sv/archnon/run
fi

if [ ! -f /etc/init.d/archnon ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/archnon
    cat << 'EOT' > /etc/init.d/archnon
#!/sbin/openrc-run
name=ArchNoN service
command="archnon"
command_args="start"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
depend() {
   need net
}
EOT
   chmod +x /etc/init.d/archnon >/dev/null 2>&1
fi

# Torrc && Script Functions

if ! $(tor --verify-config >/dev/null 2>&1); then

echo -e "\n${RED}[${YELLOW}warn${RED}]${GREEN} Tor's configuration file is not valid, Try ${YELLOW}'sudo archnon config-reset'${NC}"

fi

help(){
   echo -e "\n${P}[${BLUE} ArchNoN Anonimation Tool ${P}] ${YELLOW}-> [ ${BLUE}v3.2 ${YELLOW}]${NC}"
   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Developed by: ${RED}newmasterone27@gmail.com${NC}"
   echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} Usage:${P} sudo archnon ${P}<${NC}action${P}>${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}start${YELLOW} ] --> ${GREEN}Start ${BLUE}ArchNoN and ${YELLOW}Apply Firewall rules${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}stop${YELLOW} ] --> ${GREEN}Stop ${BLUE}ArchNoN and ${RED}Flush Firewall rules${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}restart${YELLOW} ] --> ${GREEN}Restart ${BLUE}ArchNoN${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}boot-enable${YELLOW} ] --> ${GREEN}Enable ${BLUE} ArchNoN on boot ${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}boot-disable${YELLOW} ] --> ${RED}Disable ${BLUE}ArchNoN on boot ${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}myip${YELLOW} ] --> ${GREEN}Show ${BLUE}Public IP Address${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}changeid${YELLOW} ] --> ${GREEN}Change ${BLUE}Tor Public IP Address${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}bridges${YELLOW} ] --> ${GREEN}Load a custom ${P}Tor bridges configuration file${GREEN}, ${YELLOW}usage: ${BLUE}archnon bridges ${YELLOW}<${NC}file${YELLOW}> <${NC}kind${YELLOW}> <${NC}binary${YELLOW}>${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}config-reset${YELLOW} ] --> ${GREEN}Reset ${YELLOW}Tor's configuration file ${RED}(${P}/etc/tor/torrc${RED}) ${BLUE}to ArchNoN's default${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}config-show${YELLOW} ] --> ${GREEN}Show ${BLUE}configuration files that were touched by ArchNoN${RED} (${P}/etc/tor/torrc, /etc/resolv.conf${RED})${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}config-load${YELLOW} ] --> ${GREEN}Load a ${BLUE}custom Torrc${P}(${RED}that is the file that tor reads before start${P})${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}resolv${YELLOW} ] --> ${GREEN}Resolves ${P}.onion ${BLUE}addresses${NC}"
   echo -e "\n${YELLOW}[ ${BLUE}help${YELLOW} ] --> ${GREEN}Print this usage page${NC}"
 }

myip(){

export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Your Tor Public IP${NC}:" && curl --socks5-hostname 127.0.0.1:9150 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Your Tor ISP${NC}:" && curl --socks5-hostname 127.0.0.1:9150 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
else

   echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Your Public IP:${NC}" && curl --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Your ISP:${NC}" && curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
fi

}

start(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

sudo setenforce 0 >/dev/null 2>&1
sudo semanage permissive -a unconfined_t >/dev/null 2>&1

modprobe nft_nat >/dev/null 2>&1
modprobe nft_chain_nat >/dev/null 2>&1
modprobe nf_nat >/dev/null 2>&1

chattr -i /etc/archnon_rules.nft >/dev/null 2>&1
rm /etc/archnon_rules.nft >/dev/null 2>&1
touch /etc/archnon_rules.nft >/dev/null 2>&1

sudo nft flush ruleset

cat << EOT > /etc/archnon_rules.nft
table ip6 filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                meta l4proto ipv6-icmp icmpv6 type echo-request counter packets 0 bytes 0 drop
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
        }
}
table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                iifname "lo" counter packets 16 bytes 1581 accept
                ct state related,established counter packets 84 bytes 46784 accept
                iifname "lo" ip protocol icmp icmp type echo-request ct state related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
                oifname "lo" counter packets 10 bytes 1186 accept
                ct state new,related,established counter packets 86 bytes 48629 accept
                oifname "lo" ip protocol icmp icmp type echo-request ct state new,related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
                skuid $TOR_USER counter packets 0 bytes 0 accept
                ip daddr 127.0.0.1 udp dport 5353 counter packets 0 bytes 0 accept
                ip daddr 127.0.0.1 tcp dport 6969 counter packets 0 bytes 0 accept
                counter packets 0 bytes 0 reject
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }
}
table ip nat {
        chain OUTPUT {
                type nat hook output priority dstnat; policy accept;
                ip daddr 127.0.0.1 tcp dport 53 counter packets 0 bytes 0 redirect to :5353
                ip daddr 127.0.0.1 udp dport 53 counter packets 2 bytes 114 redirect to :5353
                skuid $TOR_USER counter packets 2 bytes 120 return
                ip daddr 127.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 192.168.0.0/16 counter packets 0 bytes 0 return
                ip daddr 10.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 172.16.0.0/12 counter packets 0 bytes 0 return
                ip daddr 169.254.0.0/16 counter packets 0 bytes 0 return
                ip daddr 255.255.255.255 counter packets 0 bytes 0 return
                ip daddr 224.0.0.0/4 counter packets 0 bytes 0 return
                udp dport 53 counter packets 0 bytes 0 redirect to :5353
                tcp flags & (fin | syn | rst | ack) == syn counter packets 1 bytes 60 redirect to :6969
        }
}
EOT

sudo iptables -I INPUT -p tcp --dport 2222 -j ACCEPT
sudo iptables -I OUTPUT -p tcp --dport 2222 -j ACCEPT

chattr +i /etc/archnon_rules.nft >/dev/null 2>&1
nft -f /etc/archnon_rules.nft

   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1
   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1
   echo -e "\n# Generated By ArchNoN #\n# File locked by chattr +i, unlock: sudo chattr -i /etc/resolv.conf\nnameserver 127.0.0.1" | tee /etc/resolv.conf >/dev/null 2>&1
   chmod 644 /etc/resolv.conf >/dev/null 2>&1
   chattr +i /etc/resolv.conf >/dev/null 2>&1

   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1

   sleep 8

   tor --User $TOR_USER --RunAsDaemon 1 --DataDirectory /var/lib/tor -f /etc/tor/torrc >/dev/null 2>&1

   if pgrep -a tor | grep -IE "tor" >/dev/null 2>&1 || ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN is running ${BLUE}(${GREEN}done${BLUE})${NC}"
   else
	 echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} For some reason script could not start...${NC}"
         exit 1
   fi
}


config(){

if ! cat /etc/tor/torrc | grep -iE "UseBridges 1" >/dev/null 2>&1 || ! cat /etc/tor/torrc | grep -iE "NOT TOUCH, THIS FILE IS CUSTOM LOAD" >/dev/null 2>&1; then

   chattr -i /etc/tor/torrc >/dev/null 2>&1
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by ArchNoN ---> #
# File locked by chattr +i, unlock: sudo chattr -i /etc/tor/torrc

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 20
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1

EOT

chattr +i /etc/tor/torrc >/dev/null 2>&1

fi
   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif echo $TOR_USER >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   else
        echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} ArchNoN needs a tor user to apply firewall rules and it could not be found, thats weird !!!${NC}, you must create an user 'tor' manually${NC}"
        exit 1
   fi
	
   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   chmod 700 /var/lib/tor >/dev/null 2>&1
   chattr +i /etc/tor/torrc >/dev/null 2>&1
   start
}

function stop(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then

   echo -e "\n${RED}[${YELLOW}warn${RED}]${GREEN} Requested action: ${YELLOW}'stop' ${GREEN}ArchNoN${NC}"

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1
   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "\n# <--- Generated by ArchNoN ---> #\n# File locked by chattr +i, unlock: sudo chattr -i /etc/resolv.conf\nnameserver 9.9.9.9" | tee /etc/resolv.conf >/dev/null 2>&1
   chattr +i /etc/resolv.conf >/dev/null 2>&1

   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1

   sleep 8

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1
   sudo nft flush ruleset >/dev/null 2>&1

   echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} ArchNoN has been stopped.${NC}"
else
   echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} ArchNoN is not running${NC}"
   exit 1
fi

}


# Function Calls (parameters)

while [ $# -gt 0 ]; do

case $1 in

start)

mode=1

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'Start'${NC}"

if ! ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || ! pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then
    echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN is starting${NC}"
    config
    exit 0
    shift
    break
else
    echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already running${NC}"
    echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} Note: To resolv ${P}.onion ${GREEN}addresses you must use: '${YELLOW}archnon link <link>'${NC}"
    exit 0
    shift
    break
fi

shift

break

;;

stop)

mode=2

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'Stop'${NC}"

stop

shift

break

;;

myip)

mode=4

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'get_id'${NC}"

myip

shift

break

;;

changeid)

mode=5

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'newnym'${NC}"

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9151 >/dev/null 2>&1

   myip

else
   echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} ArchNoN is not running${NC}"
   exit 1
fi

shift

break

;;

boot-enable)

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'boot-enable'${NC}"

if [ -f /etc/systemd/system/archnon.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled archnon >/dev/null 2>&1; then
       echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already enabled${NC}"
    else
        systemctl enable archnon >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been enable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not enable ArchNoN, check your permissions over the system${NC}"
    fi
fi

if [ -f /etc/sv/archnon/run ] && command -v runit >/dev/null 2>&1; then

	if [ -d /run/runit/service ]; then
	    RSDIR=/run/runit/service
	elif [ -d /etc/service ]; then
	      RSDIR=/etc/service
	elif [ -d /var/run/service ]; then
	      RSDIR=/var/run/service
	fi

      if ls -l $RSDIR/archnon/ >/dev/null 2>&1; then
            echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already enabled${NC}"
      else
           ln -s /etc/sv/archnon $RSDIR >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been enable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not enable ArchNoN, check your permissions over the system${NC}"
      fi
fi

if [ -f /etc/init.d/archnon ] && command -v rc-update >/dev/null 2>&1; then

      if sudo rc-update | grep -iE "archnon" >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already enabled${NC}"
      else
           sudo rc-update add archnon default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been enable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not enable ArchNoN, check your permissions over the system${NC}"
      fi
fi

shift
break
;;

boot-disable)

mode=7

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'boot-disable'${NC}"

if [ -f /etc/systemd/system/archnon.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled archnon >/dev/null 2>&1; then
        echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already disabled${NC}"
        exit 0
    else

    systemctl disable archnon >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been disable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not disable ArchNoN, check your permissions over the system${NC}"
    exit 1
    fi
fi

if [ -f /etc/sv/archnon/run ] && command -v runit  >/dev/null 2>&1; then

      if [ -d /run/runit/service ]; then
	  RSDIR=/run/runit/service

      elif [ -d /etc/service ]; then
	      RSDIR=/etc/service
	
      elif [ -d /var/run/service ]; then
	      RSDIR=/var/run/service
      fi

      if ! ls -l $RSDIR/archnon/ >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already disabled${NC}"
           exit 0
      else

      rm -rf $RSDIR/archnon >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been disable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not disable ArchNoN, check your permissions over the system${NC}"
      exit 1
      fi
fi

if [ -f /etc/init.d/archnon ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "archnon" >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} ArchNoN is already disabled${NC}"
           exit 0
      else

      rc-update del archnon default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} ArchNoN has been disable${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Could not disable ArchNoN, check your permissions over the system${NC}"
      exit 1
      fi
fi

shift
break
;;

bridges)

if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

mode=9
file=$2
kind=$3
bin=$4

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'Bridges'${NC}"

chattr -i /etc/tor/torrc >/dev/null 2>&1
rm /etc/tor/torrc >/dev/null 2>&1
touch /etc/tor/torrc >/dev/null 2>&1

if [[ -z "$file" || ! -f "$file" || -z "$kind" || ! "$bin" || -z "$bin" ]]; then
    echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${YELLOW} Usage: ${BLUE}sudo archnon bridges ${YELLOW}<${BLUE}file${YELLOW}> ${YELLOW}<${BLUE}kind${YELLOW}> ${YELLOW}<${BLUE}bin${YELLOW}>${NC}"
    echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} EXAMPLE: ${BLUE}sudo archnon bridges ${YELLOW}bridges.txt obfs4 /usr/bin/obfs4proxy${NC}"
    echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} The file should ONLY contain the bridges info in this format: ${YELLOW}<${NC}Prefix: ${YELLOW}'bridge'> <${NC}type${YELLOW}> [${NC}IP${YELLOW}]${GREEN}:${YELLOW}[${NC}PORT${YELLOW}] [${NC}fingerprint${YELLOW}] [${NC}Key=value${YELLOW}]${NC}"
    exit 1
fi

bridges=$(cat "$file")

echo -e "\n# <--- Generated by ArchNoN ---> #\n# Bridges Configuration #\n# File locked by chattr +i, unlock: sudo chattr -i /etc/tor/torrc #\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nMaxCircuitDirtiness 20 \nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nDNSPort 127.0.0.1:5353\nControlPort 127.0.0.1:9151\nSocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1\n" | tee /etc/tor/torrc >/dev/null 2>&1

if tor --verify-config >/dev/null 2>&1; then
   echo -e "\n${P}[${GREEN}notice${P}]${GREEN} Configuration was modified${BLUE}(${GREEN}done${BLUE})${NC}"
   echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} You must restart ArchNoN now${NC}"
   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc
   chown -R $TOR_USER:$TOR_USER /var/lib/tor
   chattr +i /etc/tor/torrc >/dev/null 2>&1
   exit 0
else
   echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Configuration File is not valid, try ${YELLOW}'archnon config-reset'${NC}"
   exit 1
fi

shift
break

;;

config-reset)
mode=10
   if [ $EUID -ne 0 ]; then
	echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
	exit 1
   fi

   echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} Requested file: ${RED}(${YELLOW}/etc/tor/torrc${RED})${NC}"
   chattr -i /etc/tor/torrc >/dev/null 2>&1
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by ArchNoN ---> #
# File locked by chattr +i, unlock: chattr -i /etc/tor/torrc

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 20
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1

EOT

chattr +i /etc/tor/torrc

echo -e "\n${P}[${YELLOW}warn${P}]${GREEN} Configuration file touched ${BLUE}(${GREEN}done${BLUE})${NC}"

shift
break
;;

restart)
mode=11
if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${P} Requested action: ${YELLOW}'Restart'${NC}"

pkill -9 tor >/dev/null 2>&1
pkill -9 NetworkManager >/dev/null 2>&1

config

shift
break
;;

--help|-help|help|-h)

mode=13

help

shift

break

;;

resolv)

mode=14

link=$2

if [ -z "$link" ]; then
  echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: Missing destination a address${NC}"
  exit 1
fi

if pgrep -a tor | grep -IE "tor" >/dev/null 2>&1 || ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then


export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )

echo -e "\n${P}[${GREEN}notice${P}]${GREEN} Resolving ${YELLOW}'$link'${GREEN}...${NC}"
curl --socks5-hostname 127.0.0.1:9150 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" "$link" && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${YELLOW} "$link" ${GREEN}resolved${NC}" || echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} An error ocurred while trying to resolv: $link${NC}"
exit 0

else
   echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} ArchNoN is not running${NC}"
   exit 1
fi

shift
break
;;

config-show)
mode=15

if [ -f /etc/tor/torrc ] && [ -f /etc/resolv.conf ]; then
  echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} Requested Tor's file ${P}(${BLUE}/etc/tor/torrc${P}): ${NC}"
    cat /etc/tor/torrc
    echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} Requested DNS's file ${P}(${BLUE}/etc/resolv.conf${P}): ${NC}"
    cat /etc/resolv.conf
else
  echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Requested file not found: ${RED}(${YELLOW}/etc/tor/torrc, /etc/resolv.conf${RED})${NC}"
  exit 1
fi

shift
break
;;

config-load)
mode=16

if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: user is not ${RED}root${NC}"
    exit 1
fi

file=$2

if [ -z $file ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: Missing file${NC}"
    echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} usage: ${BLUE}sudo archnon config-load ${YELLOW}<${NC}file${YELLOW}>${NC}"
    exit 1
fi

if [ ! -f $file ]; then
    echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: ${RED}No such file !!${NC}"
    exit 1
fi


if [ -f /etc/tor/torrc ]; then
    
    chattr -i /etc/tor/torrc >/dev/null 2>&1
    
    rm /etc/tor/torrc >/dev/null 2>&1
    touch /etc/tor/torrc >/dev/null 2>&1
    
    echo -e "\n# NOT TOUCH, THIS FILE IS CUSTOM LOAD #" >> /etc/tor/torrc

    cat "$file" >> /etc/tor/torrc && echo -e "\n${BLUE}[${YELLOW}warn${BLUE}]${GREEN} File touched${BLUE}(${GREEN}done${BLUE})${NC}"
    chattr +i /etc/tor/torrc >/dev/null 2>&1
    
    if id debian-tor >/dev/null 2>&1; then
         export TOR_USER="debian-tor"
    elif id tor >/dev/null 2>&1; then
         export TOR_USER="tor"
    elif id toranon >/dev/null 2>&1; then
         export TOR_USER="toranon"
    else
	export TOR_USER=$(id 0)
    fi

    chwon -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1

    if tor --verify-config >/dev/null 2>&1; then
	echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Configuration was valid, you must restart ArchNoN to apply it${NC}"
        exit 0
    else
	echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: Configuration was not valid !!${NC}"
	exit 1
    fi
else
	echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: Requested file: ${P}(${YELLOW}/etc/tor/torrc${P}) ${RED}not found !${NC}"
	exit 1
fi

shift
break
;;

--*|-*|*)
mode=17

echo -e "\n${RED}[${GREEN}err${RED}]${GREEN} Bad usage: unknown action ${YELLOW}'$1'${GREEN}, see ${GREEN}'archnon help'${GREEN}${NC}"

exit 1

shift
break
;;

esac
done

# This dumb condition that throws a Help page

if [[ -z "$mode" ]]; then
    help
    exit 1
fi
