#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

usage(){
echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} usage: ${P}neptuner ${NC}<${LB}option${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}1${BLUE}]${ORANGE} -L${BLUE}|${ORANGE}--link ${NC}<${P}link${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}2${BLUE}]${ORANGE} -S${BLUE}|${ORANGE}--socks-addr ${NC}<${P}addr${NC}> <${P}link${NC}>${NC}"
echo -e "\n${BLUE}[${YELLOW}3${BLUE}]${ORANGE} -C${BLUE}|${ORANGE}--change ${NC}<${P}addr_for_resolv.conf${NC}>${NC}"
}

if ! command -v figlet >/dev/null 2>&1; then
        if [[ $(command -v apt) ]]; then
                if ! apt install -y figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v pacman) ]]; then
                if ! pacman -Sy --noconfirm --needed --overwrite "*" figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v dnf) ]]; then
                if ! dnf install -y --allowerasing figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v yum) ]]; then
                if ! yum install -y figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v xbps-install) ]]; then
                if ! xbps-install -Sy -f -y "*" figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v zypper) ]]; then
                if ! zypper install figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v apk) ]]; then
                if ! apk add --no-cache figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        elif [[ $(command -v emerge) ]]; then
                if ! emerge -v --oneshot --keep-going figlet; then
                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}figlet${NC}"
                exit 1
                fi
        else
                echo -e "\n${RED}[${NC}-${RED}]${NC} Not common: ${RED}Unsuported pkg manager, please install: ${ORANGE}'figlet'${NC}"
                exit 1
        fi
fi


echo -e "${P}" && figlet neptuneresolv
echo -n -e "${ORANGE}v1.0.0.2 ${LB}-->${P} neptune's DNS resolution Tool${NC}"
echo -e "\n"
echo -e "${ORANGE}[${YELLOW}*${ORANGE}] ${GREEN}Coded By: ${ORANGE}gmasterone@duck.com${NC}"

while [ $# -gt 0 ]; do
        case $1 in
        -L|--link)
        mode=1
        link=$2

        if [ -z $link ]; then
            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing link argument${NC}"
            echo -e "\n${ORANGE}[${YELLOW}!${ORANGE}]${NC} usage: ${LB}neptuner ${P}-L ${YELLOW}<${NC}link${YELLOW}>${NC}"
            exit 1
        else
            SOCKS5=127.0.0.1:9150
            echo -e "\n${LB}[${YELLOW}*${LB}]${BLUE} SOCKS5 Address: ${ORANGE}127.0.0.1${GREEN}:${YELLOW}9150${NC}"
            echo -e "\n${BLUE}[${YELLOW}!${BLUE}]${LB} Trying ${P}"$link"${NC}"
            curl --socks5-hostname $SOCKS5 "$link" && echo -e "\n${BLUE}[${ORANGE}+${BLUE}]${GREEN} Address Resolved${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not resolv: ${YELLOW}"$link"${NC}"
            exit 0
        fi

        shift
        break

        ;;

        -S|--socks-addr)
        mode=2
        ADDR=$2
        link=$3

        if [[ -z $ADDR || -z $link ]]; then
            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing values${NC}"
            echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${NC} usage: ${LB}neptuner ${P}--socks-addr ${NC}<${BLUE}addr${NC}> <${BLUE}link${NC}>${NC}"
            exit 1
        else
           SOCKS5="$ADDR"
           echo -e "\n${LB}[${YELLOW}*${LB}]${BLUE} SOCKS5 Address: ${ORANGE}$ADDR${NC}"
           echo -e "\n${BLUE}[${YELLOW}!${BLUE}]${LB} Trying ${P}"$link"${NC}"
           curl --socks5-hostname $SOCKS5 "$link" && echo -e "\n${BLUE}[${ORANGE}+${BLUE}]${GREEN} Address Resolved${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not resolv: ${YELLOW}"$link"${NC}"
           exit 0
        fi

        shift
        break

        ;;
	
	-C|--change)
	mode=3
	addr=$2

	if ! [ -f /etc/resolv.conf ]; then
		echo -e "\n${RED}[${NC}err${RED}]${NC} Not common: ${ORANGE}'/etc/resolv.conf', ${RED}no such file !${NC}"
		exit 1
	fi

	if [ -z $addr ]; then
		echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}Missing Addr${NC}"
		echo -e "\n${RED}[${ORANGE}warn${RED}]${NC} usage: ${GREEN}sudo neptunec ${NC}<${P}addr${NC}>"
		exit 1
	else

	chattr -i /etc/resolv.conf
	rm /etc/resolv.conf
	touch /etc/resolv.conf

	echo -e "# <--- Generated By neptune for system DNS --->#\nnameserver $addr" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Now DNS Points to: ${ORANGE}$addr${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED} Could not change DNS !${NC}"
	exit 0

	fi

	shift
	break
	;;

        --help|-help|help)
        mode=4

        usage
        exit 1

        shift
        break

        ;;

        --*|-*|*)
        mode=4
        usage

        echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}unknown option: ${YELLOW}'$1'${NC}"

        shift
        break
        exit 1

        ;;

esac
done

if [ -z "$mode" ]; then
    usage
    exit 1
fi
