#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

# Dependencies && pkg managers

if ! (command -v nc >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v nft >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1 && command -v chattr >/dev/null 2>&1 && command -v i2pd >/dev/null 2>&1); then

       if [[ $(command -v apt) ]]; then

           pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

           if ! apt install "${pkgs[@]}" -y; then
                  echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                  exit 1
               fi
               wait

        elif [[ $(command -v pacman) ]]; then

              pkgs=( openbsd-netcat curl tor nftables procps-ng networkmanager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! pacman -Syy "${pkgs[@]}" --needed --noconfirm --overwrite "*"; then
                        echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                    exit 1
                 fi
                 wait

        elif [[ $(command -v dnf) ]]; then

              pkgs=( epel-release nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! dnf -y install --allowerasing "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v yum) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! yum -y install "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v zypper) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! zypper install "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v apk) ]]; then

              pkgs=( netcat-openbsd curl tor nftables procps networkmanager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! apk add --no-cache "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v xbps-install) ]]; then

              pkgs=( openbsd-netcat curl tor iproute2 coreutils util-linux bash nftables sudo procps-ng NetworkManager figlet e2fsprogs i2pd)

              if ! xbps-install -Sy -f -y "*" "${pkgs[@]}"; then
                     echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                     exit 1
                  fi
                  wait
        elif [[ $(command -v emerge) ]]; then

              pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)

              if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
                    echo -e "${RED}[${NC}err${RED}]${NC} Missing PKGs: ${RED}(${NC}${pkgs[@]}${RED})${NC}"
                    exit 1
              fi
              wait
        else
              pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo figlet e2fsprogs i2pd)
              echo -e "${RED}[${NC}err${RED}]${NC} Missing dependencies !!${NC}"
              echo -e "${RED}[${NC}err${RED}]${NC} Not common: ${RED}unsuported pkg manager, please, install: ${BLUE}(${YELLOW}${pkgs[@]}${BLUE})${NC}"
              exit 1
        fi
fi

# Banner here so it checks dependencies first

echo -e "${BLUE}" && figlet numb
echo -n -e "${P}v3.0.0.10 ${LB}-->${ORANGE} Portable Bash Based Anonymation Tool${NC}"
echo -e "\n"
echo -e "${BLUE}[${GREEN}*${BLUE}]${LB} Coded by: ${ORANGE}gmasterone@duck.com${NC}"

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/numb.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/numb.service
    cat << 'EOT' > /etc/systemd/system/numb.service
[Unit]
Description=numb
[Service]
Type=forking
ExecStart=numb start
RemainAfterExit=yes
User=root
[Install]
WantedBy=multi-user.target
EOT
fi

if [ ! -f /etc/sv/numb/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/numb/
    touch /etc/sv/numb/run
    cat << 'EOT' > /etc/sv/numb/run
#!/bin/sh
exec numb start
EOT
    chmod +x /etc/sv/numb/run
fi

if [ ! -f /etc/init.d/numb ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/numb
    cat << 'EOT' > /etc/init.d/numb
#!/sbin/openrc-run
name=numb
command="numb"
command_args="start"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
depend() {
   need net
}
EOT
   chmod +x /etc/init.d/numb >/dev/null 2>&1
fi


# Bind Addr
# Default: 127.0.0.1(loopback/lo/localhost)

IFNAME=lo
ADDR=127.0.0.1

# Tor Ports
# Default order: 6969, 5353, 9150, 9151, 8181

TRANS=6969
DNS=5353
SOCKS=9150
CONTROL=9151
HTTP=8181 

# I2pd Ports
# Default order: 7070, 4444, 4447 

I2pd_HTTP=7070
I2pd_HTTP_proxy=4444
I2pd_socks=4447

# Configuration Files
# Default order: /etc/tor/torrc, /etc/i2pd.conf, /etc/numb_rules.nft

TORRC=/etc/tor/torrc
I2PDCONF=/etc/i2pd.conf
FWFILE=/etc/numb_rules.nft

# Script Functions

torrc(){
if ! $(tor --verify-config >/dev/null 2>&1); then

echo -e "\n${RED}[${NC}err${RED}] ${NC}Bad usage: ${RED}Invalid Torrc${NC}, Try ${ORANGE}'archconfig reset'${NC}"
exit 1

fi
}

help(){
echo -e "\n${BLUE}[${LB}*${BLUE}]${GREEN} usage: ${P}numb ${NC}<${BLUE}option${NC}>"
echo -e "\n${ORANGE}[${NC}1${ORANGE}] ${LB}start: ${GREEN}start script${NC}"
echo -e "\n${ORANGE}[${NC}2${ORANGE}] ${LB}stop: ${RED}stop script${NC}"
echo -e "\n${ORANGE}[${NC}3${ORANGE}] ${LB}restart: ${YELLOW}restart ${LB}script"
echo -e "\n${ORANGE}[${NC}4${ORANGE}] ${LB}enable: ${GREEN}enable ${ORANGE}script on boot"
echo -e "\n${ORANGE}[${NC}5${ORANGE}] ${LB}disable: ${RED}disable ${ORANGE}script on boot"
echo -e "\n${ORANGE}[${NC}6${ORANGE}] ${LB}myip: ${BLUE}show ${ORANGE}Your IP${NC}"
echo -e "\n${ORANGE}[${NC}7${ORANGE}] ${LB}changeid: ${ORANGE}change ${P}Your Tor IP${NC}"
exit 1
}

myip(){

if pgrep -x tor >/dev/null 2>&1 && pgrep -a i2pd >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Reverse Address:${GREEN} $(curl -Ssq --socks5-hostname $ADDR:$SOCKS ifconfig.co)"

else

   echo -e "\n${RED}[${NC}notice${RED}]${GREEN} Reverse Address:${NC} $(curl -Ssq ifconfig.co)"

   exit 0
fi

}

start(){

sudo setenforce 0 >/dev/null 2>&1
sudo semanage permissive -a unconfined_t >/dev/null 2>&1

modprobe nft_nat >/dev/null 2>&1
modprobe nft_chain_nat >/dev/null 2>&1
modprobe nf_nat >/dev/null 2>&1

chattr -i $FWFILE >/dev/null 2>&1

rm $FWFILE >/dev/null 2>&1
touch $FWFILE >/dev/null 2>&1

sudo nft flush ruleset >/dev/null 2>&1

cat << EOT > $FWFILE
table ip6 filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                meta l4proto ipv6-icmp icmpv6 type echo-request counter packets 0 bytes 0 drop
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
        }
}
table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                iifname "$IFNAME" counter packets 16 bytes 1581 accept
                ct state related,established counter packets 84 bytes 46784 accept
                iifname "$IFNAME" ip protocol icmp icmp type echo-request ct state related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
                oifname "$IFNAME" counter packets 10 bytes 1186 accept
                ct state new,related,established counter packets 86 bytes 48629 accept
                oifname "$IFNAME" ip protocol icmp icmp type echo-request ct state new,related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
                skuid $TOR_USER counter packets 0 bytes 0 accept
                skuid $I2P counter packets 0 bytes 0 accept
                ip daddr $ADDR tcp dport $I2pd_HTTP counter packets 0 bytes 0 accept
                ip daddr $ADDR tcp dport $I2pd_HTTP_proxy counter packets 0 bytes 0 accept
                ip daddr $ADDR tcp dport $I2pd_socks counter packets 0 bytes 0 accept
                ip daddr $ADDR udp dport $DNS counter packets 0 bytes 0 accept
                ip daddr $ADDR tcp dport $TRANS counter packets 0 bytes 0 accept
                ip daddr $ADDR tcp dport $HTTP counter packets 0 bytes 0 accept
                counter packets 0 bytes 0 reject
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }
}
table ip nat {
        chain OUTPUT {
                type nat hook output priority dstnat; policy accept;
		ip daddr $ADDR tcp dport 443 counter packets 0 bytes 0 redirect to :$I2pd_HTTP_proxy
                ip daddr $ADDR tcp dport 80 counter packets 0 bytes 0 redirect to :$I2pd_HTTP_proxy
                ip daddr $ADDR tcp dport 53 counter packets 0 bytes 0 redirect to :$DNS
                ip daddr $ADDR udp dport 53 counter packets 2 bytes 114 redirect to :$DNS
                ip daddr $ADDR tcp dport $I2pd_HTTP_proxy counter packets 0 bytes 0 return
                ip daddr $ADDR tcp dport $I2pd_socks counter packets 0 bytes 0 return
                ip daddr $ADDR tcp dport $I2pd_HTTP counter packets 0 bytes 0 return
                skuid $TOR_USER counter packets 2 bytes 120 return
                skuid $I2P counter packets 0 bytes 0 return
                ip daddr 127.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 192.168.0.0/16 counter packets 0 bytes 0 return
                ip daddr 10.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 172.16.0.0/12 counter packets 0 bytes 0 return
                ip daddr 169.254.0.0/16 counter packets 0 bytes 0 return
                ip daddr 255.255.255.255 counter packets 0 bytes 0 return
                ip daddr 224.0.0.0/4 counter packets 0 bytes 0 return
		tcp dport 53 counter packets 0 bytes 0 redirect to :$DNS
                udp dport 53 counter packets 0 bytes 0 redirect to :$DNS
                tcp flags & (fin | syn | rst | ack) == syn counter packets 1 bytes 60 redirect to :$TRANS
                }
}
EOT

chattr +i $FWFILE >/dev/null 2>&1

nft -f $FWFILE >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Firewall Applied !${NC}" || echo -e "\n${RED}[${NC}err${RED}] ${NC}unknown: ${RED}Could not apply Firewall${NC}"

sleep 1

   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} IPv6 and Pings disabled !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}could not disable IPv6 and ignore echo requests${NC}"

   sleep 1

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1
   pkill -9 i2pd >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "# Generated By numb #\nnameserver $ADDR" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} DNS Points to: ${ORANGE}$ADDR${GREEN} !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not change DNS resolv.conf${NC}"

   sleep 1

   chmod 644 /etc/resolv.conf >/dev/null 2>&1
   chattr +i /etc/resolv.conf >/dev/null 2>&1

   while ! pgrep -x NetworkManager >/dev/null 2>&1; do
      NetworkManager >/dev/null 2>&1 && continue || break
   done && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} Networking Fixed !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not fix Networking..${NC}"

   sleep 1

   tor --User $TOR_USER --RunAsDaemon 1 --DataDirectory /var/lib/tor -f $TORRC >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}Daemon Launched ${ORANGE}HTTP${GREEN}: ${BLUE}$ADDR${GREEN}:${YELLOW}$HTTP ${GREEN}!${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not launch Tor..${NC}"

   sleep 1

   i2pd --conf $I2PDCONF --daemon >/dev/null 2>&1

   pgrep -a i2pd >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${ORANGE} I2P ${GREEN}Daemon Launched, ${ORANGE}HTTP${GREEN}: ${BLUE}$ADDR${GREEN}:${YELLOW}$I2pd_HTTP_proxy ${GREEN}!${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not start I2P Daemon${NC}"
  
   sleep 1

   if pgrep -x tor >/dev/null 2>&1 && pgrep -a i2pd >/dev/null 2>&1; then

        sleep 1

        echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${GREEN} numb has been started${NC}"

   else
        sleep 1

	echo -e "${RED}[${NC}err${RED}]${NC} unknown: ${RED}could not start numb${NC}"
        exit 1
   fi
}


config(){

if ! cat $TORRC | grep -IE "NOT TOUCH, THIS FILE IS CUSTOM LOAD" >/dev/null 2>&1; then

   chattr -i $TORRC >/dev/null 2>&1

   rm $TORRC >/dev/null 2>&1
   touch $TORRC >/dev/null 2>&1

   cat << EOT > $TORRC
# <--- Generated by numb ---> #
# File locked by chattr +i, unlock: sudo chattr -i $TORRC

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort $ADDR:$TRANS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort $ADDR:$DNS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort $ADDR:$SOCKS IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ControlPort $ADDR:$CONTROL
HTTPTunnelPort $ADDR:$HTTP
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 60
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1
AvoidDiskWrites 1
EnforceDistinctSubnets 1
HardwareAccel 1

EOT

fi

if ! cat $I2PDCONF | grep -IE "NO TOUCH, CUSTOM CONFIG LOAD" >/dev/null 2>&1; then

	chattr -i $I2PDCONF >/dev/null 2>&1

	rm $I2PDCONF >/dev/null 2>&1
	touch $I2PDCONF >/dev/null 2>&1

cat << EOT > $I2PDCONF

# <--- Generated By numb ---> #
# Default template for I2P Traffic route #
# File locked with chattr +i, unlock: 'sudo chattr -i $I2PDCONF'

daemon = true

ifname = $IFNAME

ipv4 = true
ipv6 = false

[ntcp2]
enabled = true
published = false
port = 4567

[http]
enabled = true
address = $ADDR
port = $I2pd_HTTP
webroot = /
lang = english

[httpproxy]
enabled = true
address = $ADDR
port = $I2pd_HTTP_proxy
keys = transient-proxy
addresshelper = true
outproxy = http://false.i2p

[socksproxy]
enabled = true
address = $ADDR
port = $I2pd_socks
keys = transient-proxy

[sam]
enabled = true
address = $ADDR
port = 7656
portudp = 7655

[i2cp]
enabled = true
address = $ADDR
port = 7654

[i2pcontrol]

enabled = true
address = $ADDR
port = 7650

[reseed]
verify = true

[persist]
profiles = false
addressbook = false

EOT

chattr +i $TORRC >/dev/null 2>&1
chattr +i $I2PDCONF >/dev/null 2>&1

sleep 1

fi

export I2P=$(id -u i2pd)

   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}User: ${P}$TOR_USER${NC}"

   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}User: ${P}$TOR_USER${NC}"

   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} Tor ${GREEN}User: ${P}$TOR_USER${NC}"

   else
        echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not detect a Tor User${NC}"
        exit 1
   fi
	
   echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${ORANGE} I2P ${GREEN}User: ${ORANGE}$(id -un i2pd)${NC}"

   chown -R $TOR_USER:$TOR_USER $TORRC >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   chmod 700 /var/lib/tor >/dev/null 2>&1

   sleep 1

   start
}


stop(){

if pgrep -x tor >/dev/null 2>&1 || pgrep -a i2pd >/dev/null 2>&1; then
	
   sleep 1

   pkill -9 tor >/dev/null 2>&1
   pkill -9 i2pd >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Killed Daemons:${P} Networking, Tor, I2pd !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not kill some Daemons..${NC}"

   sleep 1

   chattr -i /etc/resolv.conf >/dev/null 2>&1
   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo nameserver 9.9.9.9 | sudo tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} DNS Points to secure: ${ORANGE}9${BLUE}.${ORANGE}9${BLUE}.${ORANGE}9${BLUE}.${ORANGE}9 ${GREEN}!${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not Point DNS..${NC}"

   sleep 1

   chattr +i /etc/resolv.conf >/dev/null 2>&1

   while ! pgrep -x NetworkManager >/dev/null 2>&1; do
       NetworkManager >/dev/null 2>&1 && continue || break
   done && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Networking Fixed !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not fix Networking..${NC}"

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} IPv6 and Pings are Enabled again !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not enable IPv6 and Pings..${NC}"

   sudo nft flush ruleset >/dev/null 2>&1 && echo -e "\n${RED}[${GREEN}notice${RED}]${GREEN} Firewall Rules Flushed !${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not Flush Firewall Rules..${NC}"

if ! pgrep -x tor >/dev/null 2>&1 || ! pgrep -a i2pd >/dev/null 2>&1; then
   echo -e "\n${RED}[${GREEN}notice${RED}]${NC} numb has been ${RED}stopped.${NC}"
   exit 0
else
   echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}could not stop numb${NC}"
   exit 1
fi

else
   echo -e "\n${RED}[${NC}err${RED}]${NC} Invalid Argument: ${RED}numb is not running${NC}"
   exit 1
fi

}

# Function Calls (parameters)

while [ $# -gt 0 ]; do

case $1 in

start|--start|-start)

mode=1

if [ $EUID -ne 0 ]; then
        echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
        exit 1
fi

torrc

if ! pgrep -x tor >/dev/null 2>&1 || ! pgrep -a i2pd >/dev/null 2>&1; then
    echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} Starting ${BLUE}numb's ${P}Anonymous Session${NC}"
    config
    exit 0

    shift
    break
else
    echo -e "\n${RED}[${NC}err${RED}]${NC} Invalid Argument: ${ORANGE}numb is already Running${NC}"
    exit 0

    shift
    break
fi

shift

break

;;

stop|--stop|-stop)

mode=2

if [ $EUID -ne 0 ]; then
        echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
        exit 1
fi

stop

shift

break

;;

myip|--myip|-myip|-i)

mode=3

myip

shift

break

;;

changeid|--changeid|-changeid|-c)

mode=4

if pgrep -x tor >/dev/null 2>&1 && pgrep -a i2pd >/dev/null 2>&1; then

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc $ADDR $CONTROL >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}notice${BLUE}]${P} You got a new id from Tor${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} Dont be fast, wait at least ${RED}5 secs${NC} before typing ${ORANGE}'changeid'${NC}"

else

   echo -e "\n${RED}[${NC}err${RED}]${NC} Invalid Argument: ${RED}numb is not running${NC}"
   exit 1

fi

shift

break

;;

enable|--enable|-enable)

mode=5

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
    exit 1
fi

torrc

if [ -f /etc/systemd/system/numb.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled numb >/dev/null 2>&1; then
       echo -e "\n${P}[${NC}*${P}]${NC} numb is enabled${NC}"
    else
        systemctl enable numb >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}notice${ORANGE}]${NC} Now numb is enabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not enable numb${NC}"
    fi
fi

if [ -f /etc/sv/numb/run ] && command -v runit >/dev/null 2>&1; then

        if [ -d /run/runit/service ]; then
            RSDIR=/run/runit/service
        elif [ -d /etc/service ]; then
              RSDIR=/etc/service
        elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
        fi

      if ls -l $RSDIR/numb/ >/dev/null 2>&1; then
            echo -e "\n${P}[${NC}*${P}]${NC} numb is enabled${NC}"
      else
           ln -s /etc/sv/numb $RSDIR >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}notice${ORANGE}]${NC} Now numb is enabled${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not enable numb${NC}"
      fi
fi

if [ -f /etc/init.d/numb ] && command -v rc-update >/dev/null 2>&1; then

      if sudo rc-update | grep -iE "numb" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${GREEN} numb is enabled${NC}"
      else
           sudo rc-update add numb default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}notice${ORANGE}]${NC} Now numb is enable${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not enable numb${NC}"
      fi
fi

shift
break

;;

disable|--disable|-disable)

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/numb.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled numb >/dev/null 2>&1; then
        echo -e "\n${RED}[${NC}notice${RED}]${NC} numb is disabled${NC}"
        exit 0
    else

    systemctl disable numb >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} numb has been disable${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not disable numb${NC}"
    exit 0
    fi
fi

if [ -f /etc/sv/numb/run ] && command -v runit  >/dev/null 2>&1; then

      if [ -d /run/runit/service ]; then
          RSDIR=/run/runit/service

      elif [ -d /etc/service ]; then
              RSDIR=/etc/service

      elif [ -d /var/run/service ]; then
              RSDIR=/var/run/service
      fi

      if ! ls -l $RSDIR/numb/ >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} numb is already disabled${NC}"
           exit 0
      else

      rm -rf $RSDIR/numb >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} numb has been disable${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not disable numb${NC}"
      exit 0
      fi
fi

if [ -f /etc/init.d/numb ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "numb" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} numb is already disabled${NC}"
           exit 0
      else

      rc-update del numb default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${NC} numb has been disable${NC}" || echo -e "\n${RED}[${NC}err${RED}]${NC} unknown: ${RED}Could not disable numb${NC}"
      exit 0
      fi
fi

shift
break

;;

restart|--restart|-restart)
mode=7

if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
    exit 1
fi

torrc

echo -e "\n${ORANGE}[${NC}warn${ORANGE}]${ORANGE} Restarting ${BLUE}numb's ${P}Anonymous Session${NC}"

pkill -9 tor >/dev/null 2>&1
pkill -9 NetworkManager >/dev/null 2>&1

config

shift
break

;;

--help|-help|help)
mode=9

help

shift
break

;;

--*|-*|*)
mode=10

echo -e "\n${RED}[${NC}err${RED}]${NC} Bad usage: ${RED}unknown action ${YELLOW}'$1'${NC}, see ${GREEN}'numb help'${NC}"

exit 1

shift
break

;;

esac
done

# Help page if ! mode = true
if [[ -z "$mode" ]]; then
    help
fi
