#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"

# Dependencies && pkg managers

if ! (command -v nc >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v nft >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1); then

       if [[ $(command -v apt) ]]; then
           
           pkgs=( netcat-openbsd tor curl nftables procps network-manager iproute2 coreutils util-linux bash sudo ) 

           if ! apt-get update && apt install "${pkgs[@]}" -y; then
	          echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	          exit 1
	       fi
	       wait

        elif [[ $(command -v pacman) ]]; then
              
              pkgs=( openbsd-netcat curl tor nftables procps-ng networkmanager iproute2 coreutils util-linux bash sudo ) 

              if ! pacman -Syy "${pkgs[@]}" --needed --noconfirm --overwrite "*"; then
  		        echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	            exit 1
	         fi
	         wait

        elif [[ $(command -v dnf) ]]; then
              
              pkgs=( epel-release nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo ) 

              if ! dnf -y install --allowerasing "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v yum) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo )
          
              if ! yum -y install "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v zypper) ]]; then

              pkgs=( nmap-ncat curl tor nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo )

              if ! zypper --no-interactive install "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v apk) ]]; then

              pkgs=( netcat-openbsd curl tor nftables procps networkmanager iproute2 coreutils util-linux bash sudo )
               
              if ! apk add --no-cache "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	             exit 1
	          fi
	          wait

        elif [[ $(command -v xbps-install) ]]; then

              pkgs=( openbsd-netcat curl tor iproute2 coreutils util-linux bash nftables sudo procps-ng NetworkManager ) 

              if ! xbps-install -Sy -f -y -o "*" "${pkgs[@]}"; then
	             echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
	             exit 1
	          fi
	          wait
        else
              echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox-nft is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
              exit 1
        fi
fi

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/onionbox-nft.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/onionbox-nft.service
    cat << 'EOT' > /etc/systemd/system/onionbox-nft.service
[Unit]
Description=TheOnionBox-nft Custom Service Here !!
[Service]
Type=forking
ExecStart=onionbox-nft start
RemainAfterExit=yes
User=root
[Install]
WantedBy=multi-user.target
EOT

elif [ ! -f /etc/sv/onionbox-nft/run ] && command -v runit >/dev/null 2>&1; then
      mkdir -p /etc/sv/onionbox-nft/
      touch /etc/sv/onionbox-nft/run
      cat << 'EOT' > /etc/sv/onionbox-nft/run
#!/bin/sh
exec onionbox-nft start
EOT
      chmod +x /etc/sv/onionbox-nft/run

elif [ ! -f /etc/init.d/onionbox-nft ] && command -v rc-service >/dev/null 2>&1; then
      touch /etc/init.d/onionbox-nft
      cat << 'EOT' > /etc/init.d/onionbox-nft
#!/sbin/openrc-run
name=TheOnionBox-nft service
command="onionbox-nft"
command_args="start"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
depend() {
   need net
}
EOT
      chmod +x /etc/init.d/onionbox-nft >/dev/null 2>&1
fi

# Torrc && Script Functions

if ! $(tor --verify-config >/dev/null 2>&1); then

echo -e "\n${RED}[${NC}WARN${RED}]${GREEN} Tor's configuration file is not valid.. Try ${GREEN}'sudo onionbox-nft -rc'${GREEN}, This may cause script not work !!! ${NC}"

fi

help(){
   echo -e "\n${RED}<--- [${GREEN} TheOnionBox-nft's help page ${RED}] --->${NC}"
   echo -e "\n${RED}[${YELLOW}WARN${RED}]${GREEN} You are using the nftables version, this may cause your system lose the dns resolution via normal curl, for this you must use the ${YELLOW}'-l' ${GREEN}flag below${NC}"
   echo -e "\n${P}[${NC}0${P}]${NC} --start|-start|start: ${GREEN}Start TheOnionBox-nft and Applies Firewall rules(Tor only)${NC}"
   echo -e "\n${P}[${NC}1${P}]${NC} --stop|-stop|stop: ${GREEN}Stop TheOnionBox-nft and Flushes Firewall rules(accept all)${NC}"
   echo -e "\n${P}[${NC}2${P}]${NC} --restart|-restart|restart: ${GREEN}Restart TheOnionBox-nft and Firewall rules(Tor only)${NC}"
   echo -e "\n${P}[${NC}4${P}]${NC} --boot-enable|-boot-enable|boot-enable: ${GREEN}Enables TheOnionBox-nft to start on boot ${NC}"
   echo -e "\n${P}[${NC}5${P}]${NC} --boot-disable|-boot-disable|boot-disable: ${GREEN}Disables TheOnionBox-nft to start on boot ${NC}"
   echo -e "\n${P}[${NC}6${P}]${NC} --myip|-myip|myip: ${GREEN}Show Your Public IP Address${NC}"
   echo -e "\n${P}[${NC}7${P}]${NC} --changeid|-changeid|changeid: ${GREEN}Change Your Public IP Address${NC}"
   echo -e "\n${P}[${NC}9${P}]${NC} --set-bridges|-set-bridges|-b: ${GREEN} Load a custom bridges configuration for TheOnionBox-nft, usage: ${GREEN}onionbox -b ${NC}</path/to/bridges/file> <bridges_kind> </path/to/binary>"
   echo -e "\n${P}[${NC}10${P}]${NC} --reset-config|-resset-config|-rc: ${GREEN}Reset Tor's configuration file ${YELLOW}(/etc/tor/torrc) ${GREEN}to TheOnionBox-nft default ${NC}"
   echo -e "\n${P}[${NC}11${P}]${NC} --show-config|-show-config|-sc: ${GREEN}Shows configuration files touched by TheOnionBox-nft !!${YELLOW}(/etc/tor/torrc, /etc/resolv.conf)${NC}"
   echo -e "\n${P}[${NC}12${P}]${NC} --link|-link|-l: ${GREEN}Resolves .onion links easly(requires curl)${NC}"
   echo -e "\n${P}[${NC}12${P}]${NC} --fast-shell|-fast-shell|fast-shell: ${GREEN}Launches a super user friendly shell(oshnft)${NC}"
   echo -e "\n${P}[${NC}13${P}]${NC} --help|-help|help|-h: ${GREEN}Print this help page${NC}"
}

myip(){

export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${P} Your Tor Public IP${NC}:"

   curl --socks5-hostname 127.0.0.1:9150 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${P} Your Tor ISP${NC}:"
   
   curl --socks5-hostname 127.0.0.1:9150 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
else
   
   echo -e "\n${RED}[${GREEN}INFO${RED}]${GREEN} Your Public IP ${RED}(not from Tor):${NC}"

   curl --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${RED}[${GREEN}INFO${RED}]${GREEN} Your ISP:${NC}"
 
   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
fi

}

start(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
   echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} TheOnionBox-nft is already running${NC}"
   exit 1
fi

sudo setenforce 0 >/dev/null 2>&1
sudo semanage permissive -a unconfined_t >/dev/null 2>&1

modprobe nft_nat >/dev/null 2>&1
modprobe nft_chain_nat >/dev/null 2>&1
modprobe nf_nat >/dev/null 2>&1

chattr -i /etc/onionbox.nft >/dev/null 2>&1
rm /etc/onionbox.nft >/dev/null 2>&1
touch /etc/onionbox.nft >/dev/null 2>&1

sudo nft flush ruleset

cat << EOT > /etc/onionbox.nft
table ip6 filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                meta l4proto ipv6-icmp icmpv6 type echo-request counter packets 0 bytes 0 drop
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
        }
}
table ip filter {
        chain INPUT {
                type filter hook input priority filter; policy drop;
                iifname "lo" counter packets 16 bytes 1581 accept
                ct state related,established counter packets 84 bytes 46784 accept
                iifname "lo" ip protocol icmp icmp type echo-request ct state related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
        }

        chain OUTPUT {
                type filter hook output priority filter; policy drop;
                oifname "lo" counter packets 10 bytes 1186 accept
                ct state new,related,established counter packets 86 bytes 48629 accept
                oifname "lo" ip protocol icmp icmp type echo-request ct state new,related,established counter packets 0 bytes 0 accept
                ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
                skuid $TOR_USER counter packets 0 bytes 0 accept
                ip daddr 127.0.0.1 udp dport 5353 counter packets 0 bytes 0 accept
                ip daddr 127.0.0.1 tcp dport 6969 counter packets 0 bytes 0 accept
                counter packets 0 bytes 0 reject
        }

        chain FORWARD {
                type filter hook forward priority filter; policy drop;
        }
}
table ip nat {
        chain OUTPUT {
                type nat hook output priority dstnat; policy accept;
                ip daddr 127.0.0.1 tcp dport 53 counter packets 0 bytes 0 redirect to :5353
                ip daddr 127.0.0.1 udp dport 53 counter packets 2 bytes 114 redirect to :5353
                skuid $TOR_USER counter packets 2 bytes 120 return
                ip daddr 127.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 192.168.0.0/16 counter packets 0 bytes 0 return
                ip daddr 10.0.0.0/8 counter packets 0 bytes 0 return
                ip daddr 172.16.0.0/12 counter packets 0 bytes 0 return
                ip daddr 169.254.0.0/16 counter packets 0 bytes 0 return
                ip daddr 255.255.255.255 counter packets 0 bytes 0 return
                ip daddr 224.0.0.0/4 counter packets 0 bytes 0 return
                udp dport 53 counter packets 0 bytes 0 redirect to :5353
                tcp flags & (fin | syn | rst | ack) == syn counter packets 1 bytes 60 redirect to :6969
        }
}
EOT

chattr +i /etc/onionbox.nft >/dev/null 2>&1
nft -f /etc/onionbox.nft

   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1
   pkill -f tor >/dev/null 2>&1 
   pkill -f NetworkManager >/dev/null 2>&1

  chattr -i /etc/resolv.conf >/dev/null 2>&1  
  rm /etc/resolv.conf >/dev/null 2>&1 
  touch /etc/resolv.conf >/dev/null 2>&1
  echo -e "\n# <--- Generated by TheOnionBox-nft ---> #\nnameserver 127.0.0.1" | tee /etc/resolv.conf >/dev/null 2>&1                                                                                                        
  chmod 644 /etc/resolv.conf >/dev/null 2>&1
  chattr +i /etc/resolv.conf >/dev/null 2>&1  

   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   
   sleep 8

   sudo -u $TOR_USER tor --RunAsDaemon 1 >/dev/null 2>&1
   echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft is running${BLUE}(${GREEN}done${BLUE})${NC}"
   echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} Note: To resolv ${P}.onion ${GREEN}addresses you just have to type '${YELLOW}onionbox-nft -l <link>'${NC}"
}


config(){

if ! cat /etc/tor/torrc | grep -iE "UseBridges 1" >/dev/null 2>&1; then
   
   chattr -i /etc/tor/torrc >/dev/null 2>&1
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by TheOnionBox-nft ---> #
# This Configuration File uses default's template(Provided by tool) #
# Note: if you reading this and want to use with a browser, you would likely have to manually configure a proxy and disable some features that are capable to break your anonimity !!
# This file cant be overwrited (has chattr +i), to unlock it run 'chattr -i /etc/tor/torrc'

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 20
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1

EOT

chattr +i /etc/tor/torrc >/dev/null 2>&1

fi
   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif echo $TOR_USER >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   else
        echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} TheOnionBox-nft needs a tor user to apply firewall rules and it could not be found !!!${NC}, you must do this: ${GREEN}'id tor'${NC}, then: ${GREEN}export TOR_USER='your_tor_user_output', or manually create an user 'tor'${NC}"
        exit 1
   fi

   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   start
}

function stop(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep tor >/dev/null 2>&1; then

   echo -e "\n${RED}[${GREEN}STATUS${RED}]${GREEN} Stopping TheOnionBox-nft..${NC}"
  
   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1   
   pkill -f tor >/dev/null 2>&1 
   pkill -f NetworkManager >/dev/null 2>&1 

   chattr -i /etc/resolv.conf >/dev/null 2>&1
   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "\n# <--- Generated by TheOnionBox-nft ---> #\nnameserver 9.9.9.9" | tee /etc/resolv.conf >/dev/null 2>&1
   chattr +i /etc/resolv.conf >/dev/null 2>&1
  
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1

   sleep 8

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1
   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1
   sysctl --system >/dev/null 2>&1
   sudo nft flush ruleset >/dev/null 2>&1

   echo -e "\n${RED}[${GREEN}STATUS${RED}]${GREEN} TheOnionBox-nft has been stopped.${NC}"
   echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} Note: now you wont be able to resolv .onion addresses${NC}"

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Seems like TheOnionBox-nft is not even running${NC}"
   exit 1
fi

}


# Function Calls (parameters)

while [ $# -gt 0 ]; do

case $1 in

--start|-start|start)

mode=1

if ! ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
    echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft is starting, please wait..${NC}"
    config
    exit 0
    shift
    break
else
    echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already running${NC}"
    echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} Note: To resolv ${P}.onion ${GREEN}addresses you just have to type '${YELLOW}onionbox-nft -l <link>'${NC}"
    exit 0
    shift 
    break
fi

shift

break

;;

--stop|-stop|stop)

mode=2

stop

shift

break

;;

--myip|-myip|myip)

mode=4

myip

shift

break

;;

changeid|--changeid|-changeid)

mode=5

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep tor >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${P} Changing Your Tor IP..${NC}"

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9151 >/dev/null 2>&1

   myip

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Seems like TheOnionBox-nft is not even running.. !!${NC}"
   exit 1
fi

shift

break

;;

boot-enable|--boot-enable|-boot-enable)

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Please, Run as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/onionbox-nft.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled onionbox-nft >/dev/null 2>&1; then
       echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already enable${NC}"
       exit 0
    else 
        systemctl enable onionbox-nft >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been enabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
    fi

elif [ -f /etc/sv/onionbox-nft/run ] && command -v runit  >/dev/null 2>&1; then
      if ls -l /var/service/onionbox-nft/ >/dev/null 2>&1; then
            echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already enable${NC}"
            exit 0
      else
           ln -s /etc/sv/onionbox-nft /var/service/ >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been enabled${NC}" && echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
      fi

elif [ -f /etc/init.d/onionbox-nft/ ] && command -v rc-service  >/dev/null 2>&1; then

      if rc-update | grep -iE "onionbox-nft" >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already enable${NC}"
           exit 0
      else
           rc-update add onionbox-nft default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been enabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
      fi
fi

shift
break
;;

boot-disable|--boot-disable|-boot-disable)

mode=7

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${NC} Please, Rus as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/onionbox-nft.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled onionbox-nft >/dev/null 2>&1; then
        echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already disabled${NC}"
        exit 0
    else

    systemctl disable onionbox-nft >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
    fi

elif [ -f /etc/sv/onionbox-nft/run ] && command -v runit  >/dev/null 2>&1; then
      if ! ls -l /var/service/onionbox-nft/ >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already disabled${NC}"
           exit 0
      else

      rm /var/service/onionbox-nft >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
      fi

elif [ -f /etc/init.d/onionbox-nft/ ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "onionbox-nft" >/dev/null 2>&1; then
           echo -e "\n${P}[${YELLOW}WARN${P}]${GREEN} TheOnionBox-nft is already disabled${NC}"
           exit 0
      else

      rc-update del onionbox-nft default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox-nft has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox-nft, check your permissions over the system${NC}" | exit 1
      fi
fi

shift
break
;;

--set-bridges|-set-bridges|-b)
mode=9
file=$2
kind=$3
bin=$4

chattr -i /etc/tor/torrc >/dev/null 2>&1
rm /etc/tor/torrc >/dev/null 2>&1
touch /etc/tor/torrc >/dev/null 2>&1

if [[ -z "$file" || ! -f "$file" || -z "$kind" || ! "$bin" || -z "$bin" ]]; then
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} Use: ${GREEN}sudo onionbox-nft --set-bridges </path/to/your_bridges_file> <bridges_kind> </path/to/your/proxy/bin>${NC}"
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} EXAMPLE: ${GREEN}sudo onionbox-nft -b my_bridges.txt obfs4 /usr/bin/obfs4proxy${NC}"
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} Ensure this file contains ONLY the bridges and that it follows the correct format, Ex file: ${YELLOW}<${NC}Prefix: ${YELLOW}'bridge'> <${NC}type${YELLOW}> [${NC}IP${YELLOW}]${GREEN}:${YELLOW}[${NC}PORT${YELLOW}] [${NC}fingerprint${YELLOW}] [${NC}Key=value${YELLOW}]${NC}"
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} You see this message because something failed ${RED}(You forget to give some params !!)${NC}"
    exit 1
fi

bridges=$(cat "$file")

echo -e "\n# <--- Generated by TheOnionBox-nft ---> #\n# This configuration File uses your bridges !!!#\n# This file cant be overwrited (has chattr +i), to unlock it run 'chattr -i /etc/tor/torrc'\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nMaxCircuitDirtiness 20 \nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nDNSPort 127.0.0.1:5353\nControlPort 127.0.0.1:9151\nSocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1\n" | tee /etc/tor/torrc >/dev/null 2>&1

chattr +i /etc/tor/torrc >/dev/null 2>&1

if tor --verify-config >/dev/null 2>&1; then
   echo -e "\n${P}[${GREEN}INFO${P}]${NC} Seems like your bridges are okay, try ${GREEN}'sudo onionbox-nft start or sudo onionbox-nft restart(if a current instance of the script is running)'${NC}"
   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc
   chown -R $TOR_USER:$TOR_USER /var/lib/tor
   exit 0
else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} That config is not valid !!.. Run 'cat /etc/tor/torrc' to check it, or give a valid configuration file instead of making me waste time !${NC}"
   exit 1
fi

shift
break

;;

--reset-config|-reset-config|reset-config)
mode=10
   if [ $EUID -ne 0 ]; then
	echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} You must be root${NC}"
	exit 1
   fi

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${GREEN} Reseting Tor's configuration file to TheOnionBox-nft default's${NC}"
   chattr -i /etc/tor/torrc >/dev/null 2>&1
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by TheOnionBox-nft ---> #
# This configuration File uses default's template(Provided by tool) #
# Note: if you reading this and want to use with a browser, you would likely have to manually touch the proxy configuration and set the address/ports below to avoid features that are capable to break your anonimity !!
# This file cant be overwrited (has chattr +i), to unlock it run 'chattr -i /etc/tor/torrc'  

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 20
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1

EOT

chattr +i /etc/tor/torrc

echo -e "\n${P}[${GREEN}STATUS${P}]${GREEN} Done${NC}"

shift
break
;;

--restart|-restart|restart)
mode=11
if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${NC}ERR${RED}]${GREEN} Please, Run as root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${P} TheOnionBox-nft is Restarting..${NC}"

pkill -9 tor >/dev/null 2>&1
pkill -9 NetworkManager >/dev/null 2>&1
pkill -f tor >/dev/null 2>&1
pkill -f NetworkManager >/dev/null 2>&1

config

shift
break
;;

--help|-help|help|-h)

mode=13

help

shift

break

;;


--link|link|-l)

mode=14

link=$2

if [ -z "$link" ]; then
  echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Missing a destination address${NC}"
  exit 1
fi

if pgrep tor >/dev/null 2>&1 || ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then

echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} Trying to resolv ${YELLOW}"$link"${GREEN}...${NC}"
curl --socks5-hostname 127.0.0.1:9150 "$link" && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${YELLOW} "$link" ${GREEN}resolved !${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} An error ocurred while trying to resolv: $link${NC}" | exit 1
exit 0

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} TheOnionBox-nft is not even running...${NC}"
   exit 1
fi

shift
break
;;

--show-config|-show-config|-sc)
mode=15

if [ -f /etc/tor/torrc ] && [ -f /etc/resolv.conf ]; then
    echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} Tor config: ${GREEN}"
    cat /etc/tor/torrc
    echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${GREEN} DNS config: ${GREEN}"
    cat /etc/resolv.conf
else
  echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Configuration files were not found !!!, ${YELLOW}(/etc/tor/torrc, /etc/resolv.conf)${NC}"
  exit 1
fi

echo -e "\n${NC}"

shift
break
;;

--fast-shell|-fast-shell|fast-shell)
mode=true

oshnft

shift
break
;;

--*|-*|*)
mode=14

echo -e "\n${RED}[${NC}!${RED}]${GREEN} Unknown action: ${YELLOW}'$1'${GREEN}, see ${GREEN}'onionbox-nft --help'${GREEN}, for detailed info${NC}"

exit 1

shift
break
;;

esac
done

# This dumb condition that throws a Help page

if [[ -z "$mode" ]]; then
    help
    echo -e "\n${RED}[${NC}ERR${RED}]${GREEN} TheOnionBox-nft needs an argument !!${NC}"
    exit 1
fi
