#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

NC="\e[0m"

# Dependencies && pkg managers

if ! (command -v iptables >/dev/null 2>&1 && command -v nc >/dev/null 2>&1 && command -v curl >/dev/null 2>&1 && command -v tor >/dev/null 2>&1 && command -v NetworkManager >/dev/null 2>&1 && command -v bash >/dev/null 2>&1 && command -v pkill >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1); then

       if [[ $(command -v apt) ]]; then
           
           pkgs=( netcat-openbsd tor curl iptables  procps network-manager iproute2 coreutils util-linux bash sudo ) 

           if ! apt install "${pkgs[@]}" -y; then
                  echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                  exit 1
               fi
               wait

        elif [[ $(command -v pacman) ]]; then
              
              pkgs=( openbsd-netcat curl tor iptables  procps-ng networkmanager iproute2 coreutils util-linux bash sudo ) 

              if ! pacman -Syy "${pkgs[@]}" --needed --noconfirm --overwrite "*"; then
                        echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                    exit 1
                 fi
                 wait

        elif [[ $(command -v dnf) ]]; then
              
              pkgs=( epel-release nmap-ncat curl tor iptables-nft nftables procps-ng NetworkManager iproute coreutils util-linux bash sudo ) 

              if ! dnf -y install --allowerasing "${pkgs[@]}"; then
                     echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v yum) ]]; then

              pkgs=( nmap-ncat curl tor nftables iptables procps-ng NetworkManager iproute coreutils util-linux bash sudo )
          
              if ! yum -y install "${pkgs[@]}"; then
                     echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v zypper) ]]; then

              pkgs=( nmap-ncat curl tor  procps-ng iptables NetworkManager iproute coreutils util-linux bash sudo )

              if ! zypper --no-interactive install "${pkgs[@]}"; then
                     echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v apk) ]]; then

              pkgs=( netcat-openbsd curl tor  iptables procps networkmanager iproute2 coreutils util-linux bash sudo )
               
              if ! apk add --no-cache "${pkgs[@]}"; then
                     echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                     exit 1
                  fi
                  wait

        elif [[ $(command -v xbps-install) ]]; then

              pkgs=( openbsd-netcat curl tor iproute2 coreutils iptables util-linux bash  sudo procps-ng NetworkManager ) 

              if ! xbps-install -Sy -f -y -o "*" "${pkgs[@]}"; then
                     echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
                     exit 1
                  fi
                  wait
        else
              echo -e "${RED}[${GREEN}ERR${RED}]${GREEN} Ahh.. sorry if TheOnionBox is not being perfect.. But there are some missing dependencies... Please, can you install: ${YELLOW}(${GREEN}${pkgs[@]}${YELLOW})${NC}"
              exit 1
        fi
fi

# Service Managers && Boot Automation

if [ ! -f /etc/systemd/system/onionbox.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/onionbox.service
    cat << 'EOT' > /etc/systemd/system/onionbox.service
[Unit]
Description=TheOnionBox Custom Service Here !!
[Service]
Type=forking
ExecStart=onionbox start
RemainAfterExit=yes
User=root
[Install]
WantedBy=multi-user.target
EOT

elif [ ! -f /etc/sv/onionbox/run ] && command -v runit >/dev/null 2>&1; then
      mkdir -p /etc/sv/onionbox/
      touch /etc/sv/onionbox/run
      cat << 'EOT' > /etc/sv/onionbox/run
#!/bin/sh
exec onionbox start
EOT
      chmod +x /etc/sv/onionbox/run

elif [ ! -f /etc/init.d/onionbox ] && command -v rc-service >/dev/null 2>&1; then
      touch /etc/init.d/onionbox
      cat << 'EOT' > /etc/init.d/onionbox
#!/sbin/openrc-run
name=onionbox start service
command="onionbox"
command_args="start"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
depend() {
   need net
}
EOT
      chmod +x /etc/init.d/onionbox
fi

# Torrc && Script Functions

if ! $(tor --verify-config >/dev/null 2>&1); then

echo -e "\n${RED}[${NC}WARN${RED}]${GREEN} Tor's configuration file is not valid.. Try ${GREEN}'onionbox -rc'${GREEN}, This may cause script not work !!! ${NC}"


fi

help(){
   echo -e "\n${P}<--- [${NC} TheOnionBox's help page ${P}] --->${NC}"
   echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} You are using the standard iptables based firewall version(which is the best for no SELINUX distros)${NC}"
   echo -e "\n${P}[${NC}0${P}]${NC} --start|-start|start: ${GREEN}Start TheOnionBox and Applies Firewall rules(Tor only)${NC}"
   echo -e "\n${P}[${NC}1${P}]${NC} --stop|-stop|stop: ${GREEN}Stop TheOnionBox and Flushes Firewall rules(accept all)${NC}"
   echo -e "\n${P}[${NC}2${P}]${NC} --restart|-restart|restart: ${GREEN}Restart TheOnionBox and Firewall rules(Tor only)${NC}"
   echo -e "\n${P}[${NC}4${P}]${NC} --boot-enable|-boot-enable|boot-enable: ${GREEN}Enables TheOnionBox to start on boot ${NC}"
   echo -e "\n${P}[${NC}5${P}]${NC} --boot-disable|-boot-disable|boot-disable: ${GREEN}Disables TheOnionBox to start on boot ${NC}"
   echo -e "\n${P}[${NC}6${P}]${NC} --myip|-myip|myip: ${GREEN}Show Your Public IP Address${NC}"
   echo -e "\n${P}[${NC}7${P}]${NC} --changeid|-changeid|changeid: ${GREEN}Change Your Public IP Address${NC}"
   echo -e "\n${P}[${NC}9${P}]${NC} --set-bridges|-set-bridges|-b: ${GREEN} Load a custom bridges configuration for TheOnionBox, usage: ${GREEN}onionbox -b ${NC}</path/to/bridges/file> <bridges_kind> </path/to/binary>"
   echo -e "\n${P}[${NC}10${P}]${NC} --reset-config|-resset-config|-rc: ${GREEN}Reset Tor's configuration file ${YELLOW}(/etc/tor/torrc) ${GREEN}to TheOnionBox default ${NC}"
   echo -e "\n${P}[${NC}11${P}]${NC} --show-config|-show-config|-sc: ${GREEN}Shows configuration files touched by TheOnionBox !!${YELLOW}(/etc/tor/torrc, /etc/resolv.conf)${NC}"
   echo -e "\n${P}[${NC}12${P}]${NC} --link|-link|-l: ${GREEN}Resolves .onion links easly(requires curl)${NC}"
   echo -e "\n${P}[${NC}12${P}]${NC} --fast-shell|-fast-shell|fast-shell: ${GREEN}Launches a super user friendly shell(osh)${NC}"
   echo -e "\n${P}[${NC}13${P}]${NC} --help|-help|help|-h: ${GREEN}Print this help page${NC}"
}


myip(){

export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${P} Your Tor Public IP${NC}:"

   curl --socks5-hostname 127.0.0.1:9150 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${P} Your Tor ISP${NC}:"
   
   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'

else
   
   echo -e "\n${RED}[${GREEN}INFO${RED}]${GREEN} Your Public IP ${RED}(not from Tor):${NC}"

   curl --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip

   echo -e "\n${RED}[${GREEN}INFO${RED}]${GREEN} Your ISP:${NC}"
 
   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
fi

}

start(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
   echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} TheOnionBox is already running${NC}"
   exit 1
fi
   # If any nft rule was applied before
   
   sudo nft flsuh ruleset >/dev/null 2>&1  

   mods=( ip_tables iptable_filter x_tables xt_conntrack ipt_REJECT iptable_mangle iptable_nat ipt_MASQUERADE nft_tables )

   for i in "${mods[@]}"; do
         lsmod | grep "$i" >/dev/null 2>&1 || modprobe $i >/dev/null 2>&1
   done

   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1

   sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1

   sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1

   sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1

   sysctl --system >/dev/null 2>&1

   pkill -9 tor >/dev/null 2>&1 
   pkill -f tor >/dev/null 2>&1

   pkill -9 NetworkManager >/dev/null 2>&1
   pkill -f NetworkManager >/dev/null 2>&1

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "\n# <--- Generated by TheOnionBox ---> #\n# [ WARN ] If you ran start|restart, this file will likely act as a read-only(chmod 600), this is because sometimes NetworkManager likes to overwrite it, which is bad if you are using this script !!. Anyways, if you want to unlock it, simply run 'chattr -i /etc/resolv.conf' as root\nnameserver 127.0.0.1" | tee /etc/resolv.conf >/dev/null 2>&1

   chmod 644 /etc/resolv.conf >/dev/null 2>&1

   chattr +i /etc/resolv.conf >/dev/null 2>&1

   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1

   sleep 8

   sudo -u $TOR_USER tor --RunAsDaemon 1 >/dev/null 2>&1

   sudo ip6tables -F >/dev/null 2>&1

   sudo ip6tables -t nat -F >/dev/null 2>&1

   sudo ip6tables -t mangle -F >/dev/null 2>&1

   sudo ip6tables -A INPUT -p icmpv6 --icmpv6-type echo-request -j DROP >/dev/null 2>&1

   sudo ip6tables -P INPUT DROP >/dev/null 2>&1

   sudo ip6tables -P FORWARD DROP >/dev/null 2>&1

   sudo ip6tables -P OUTPUT DROP >/dev/null 2>&1

   sudo iptables -F >/dev/null 2>&1

   sudo iptables -X >/dev/null 2>&1

   sudo iptables -A INPUT -i lo -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -o lo -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -i lo -p icmp --icmp-type echo-request -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -o lo -p icmp --icmp-type echo-request -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT >/dev/null 2>&1

   sudo iptables -A INPUT -p icmp --icmp-type echo-request -j DROP >/dev/null 2>&1

   sudo iptables -A OUTPUT -p icmp --icmp-type echo-request -j DROP >/dev/null 2>&1

   sudo iptables -A OUTPUT -m owner --uid-owner $TOR_USER -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -p udp -d 127.0.0.1 --dport 5353 -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -p tcp -d 127.0.0.1 --dport 6969 -j ACCEPT >/dev/null 2>&1

   sudo iptables -A OUTPUT -j REJECT >/dev/null 2>&1

   sudo iptables -t nat -F >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_USER -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 127.0.0.0/8 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 192.168.0.0/16 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 10.0.0.0/8 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 172.16.0.0/12 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 169.254.0.0/16 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 255.255.255.255/32 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -d 224.0.0.0/4 -j RETURN >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1

   sudo iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 6969 >/dev/null 2>&1

   sudo iptables -t nat -I OUTPUT -d 127.0.0.1 -p udp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1

   sudo iptables -t nat -I OUTPUT -d 127.0.0.1 -p tcp --dport 53 -j REDIRECT --to-ports 5353 >/dev/null 2>&1
   
   # if you use ssh

   #sudo iptables -I INPUT -p tcp --dport 22 -j ACCEPT >/dev/null 2>&1

   #sudo iptables -I INPUT -p tcp --dport 22 -j ACCEPT >/dev/null 2>&1

   sudo iptables -P OUTPUT DROP >/dev/null 2>&1

   sudo iptables -P INPUT DROP >/dev/null 2>&1

   sudo iptables -P FORWARD DROP >/dev/null 2>&1

   echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox is running${BLUE}(${GREEN}done${BLUE})${NC}"
}

config(){

if ! cat /etc/tor/torrc | grep -iE "UseBridges 1" >/dev/null 2>&1; then
   chattr -i /etc/tor/torrc
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by TheOnionBox ---> #
# This Configuration File uses default's template(Provided by tool) #
# Note: if you reading this and want to use with a browser, you would likely have to manually configure a proxy and disable some features that are capable to break your anonimity !!

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 5
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1
EOT

chattr +i /etc/tor/torrc

fi
   if id debian-tor >/dev/null 2>&1; then
       export TOR_USER="debian-tor"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id tor >/dev/null 2>&1; then
       export TOR_USER="tor"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif id toranon >/dev/null 2>&1; then
       export TOR_USER="toranon"
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   elif echo $TOR_USER >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${GREEN} The Tor user has been detected as: ${P}$TOR_USER${NC}"
   else
        echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} TheOnionBox needs a tor user to apply firewall rules and it could not be found !!!${NC}, you must do this: ${GREEN}'id tor'${NC}, then: ${GREEN}export TOR_USER='your_tor_user_output', or manually create an user 'tor'${NC}"
        exit 1
   fi

   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1
   chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
   start
}

stop(){

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Perform this action as ${RED}root${NC}"
    exit 1
fi

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep tor >/dev/null 2>&1; then

   echo -e "\n${RED}[${GREEN}STATUS${RED}]${GREEN} Stopping TheOnionBox..${NC}"

   pkill -9 tor >/dev/null 2>&1
   pkill -9 NetworkManager >/dev/null 2>&1   
   pkill -f NetworkManager >/dev/null 2>&1 
   pkill -f tor >/dev/null 2>&1 

   chattr -i /etc/resolv.conf >/dev/null 2>&1

   rm /etc/resolv.conf >/dev/null 2>&1
   touch /etc/resolv.conf >/dev/null 2>&1

   echo -e "\n# <--- Generated by TheOnionBox ---> #\n# WARN: This file is blocked and works as read-only file (chmod 600), run 'chattr -i /etc/resolv.conf' to unlock it, this is to o protect you from someone/something that wants to overwrite it, also, the selected address is part of "0 Eyes" privacy's policy(no is saving any kind of information about you, cuz no one is seeing you)\nnameserver 9.9.9.9" | tee /etc/resolv.conf >/dev/null 2>&1

   chattr +i /etc/resolv.conf >/dev/null 2>&1
  
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   NetworkManager >/dev/null 2>&1
   
   sleep 8

   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1

   sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1

   sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1

   sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1

   sysctl --system >/dev/null 2>&1

   sudo nft flsuh ruleset >/dev/null 2>&1  

   mods=( ip_tables iptable_filterx_tables nf_conntrack xt_conntrack ipt_REJECT iptable_mangle nf_nat iptable_nat ipt_MASQUERADE )
   for i in "${mods[@]}"; do
       lsmod | grep $i >/dev/null 2>&1 || modprobe $i >/dev/null 2>&1
   done

   sudo ip6tables -F >/dev/null 2>&1

   sudo ip6tables -t nat -F >/dev/null 2>&1

   sudo ip6tables -t mangle -F >/dev/null 2>&1

   sudo ip6tables -P INPUT ACCEPT >/dev/null 2>&1

   sudo ip6tables -P FORWARD ACCEPT >/dev/null 2>&1

   sudo ip6tables -P OUTPUT ACCEPT >/dev/null 2>&1

   sudo iptables -F >/dev/null

   sudo iptables -X >/dev/null

   sudo iptables -t nat -X >/dev/null

   sudo iptables -t nat -F >/dev/null

   sudo iptables -P INPUT ACCEPT >/dev/null

   sudo iptables -P FORWARD ACCEPT >/dev/null

   sudo iptables -P OUTPUT ACCEPT >/dev/null 

   echo -e "\n${RED}[${GREEN}STATUS${RED}]${GREEN} The OnionBox has been stopped${NC}"

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Seems like The OnionBox is not even running${NC}"
   exit 1
fi

}


# Function Calls (parameters)

while [ $# -gt 0 ]; do

case $1 in

--start|-start|start)

mode=1

if ! ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
    echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox is starting, please wait..${NC}"
    config
    exit 0
    shift
    break
else
    echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already running${NC}"
     echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} Note: From now you must use the feature '${YELLOW}onionbox -l <your_link_here>'${GREEN} to resolv any link(can aslo resolv ${P}.onion${GREEN}), the reason is the strict firewall rules${NC}"
    exit 0
    shift 
    break
fi

shift

break

;;

--stop|-stop|stop)

mode=2

stop

shift

break

;;

--myip|-myip|myip)

mode=4

myip

shift

break

;;

changeid|--changeid|-changeid)

mode=5

if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep tor >/dev/null 2>&1; then

   echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${P} Changing Your Tor IP..${NC}"

   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9151 >/dev/null 2>&1

   myip

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Seems like The OnionBox is not even running.. !!${NC}"
   exit 1
fi

shift

break

;;
boot-enable|--boot-enable|-boot-enable)

mode=6

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Please, Run as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/onionbox.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled onionbox >/dev/null 2>&1; then
       echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already enable${NC}"
       break
    else 
        systemctl enable onionbox >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been enabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox, check your permissions over the system${NC}" | exit 1
        break
    fi

elif [ -f /etc/sv/onionbox/run ] && command -v runit  >/dev/null 2>&1; then
      if ls -l /var/service/onionbox/ >/dev/null 2>&1; then
            echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already enable${NC}"
            break
      else
           ln -s /etc/sv/onionbox /var/service/ >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been enabled${NC}" && echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox, check your permissions over the system${NC}" | exit 1
           break
      fi

elif [ -f /etc/init.d/onionbox/ ] && command -v rc-service  >/dev/null 2>&1; then

      if rc-update | grep -iE "onionbox" >/dev/null 2>&1; then
           echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already enable${NC}"
           break
      else
           rc-update add onionbox default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been enabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not enable TheOnionBox, check your permissions over the system${NC}" | exit 1
           break
      fi
fi

shift
break
;;

boot-disable|--boot-disable|-boot-disable)

mode=7

if [ "$EUID" -ne 0 ]; then
    echo -e "\n${RED}[${GREEN}ERR${RED}]${NC} Please, Rus as ${RED}root${NC}"
    exit 1
fi

if [ -f /etc/systemd/system/onionbox.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled onionbox >/dev/null 2>&1; then
        echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already disabled${NC}"
        break
    else

    systemctl disable onionbox >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox, check your permissions over the system${NC}" | exit 1
        break
    fi

elif [ -f /etc/sv/onionbox/run ] && command -v runit  >/dev/null 2>&1; then
      if ! ls -l /var/service/onionbox/ >/dev/null 2>&1; then
           echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already disabled${NC}"
           break
      else

      rm /var/service/onionbox >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox, check your permissions over the system${NC}" | exit 1
           break
      fi

elif [ -f /etc/init.d/onionbox/ ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "onionbox" >/dev/null 2>&1; then
           echo -e "\n${BLUE}[${YELLOW}WARN${BLUE}]${GREEN} TheOnionBox is already disabled${NC}"
           break
      else

      rc-update del onionbox default >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${GREEN} TheOnionBox has been disabled${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Could not disable TheOnionBox, check your permissions over the system${NC}" | exit 1
      break
      fi
fi

shift
break
;;


--set-bridges|-set-bridges|-b)
mode=9
file=$2
kind=$3
bin=$4

chattr -i /etc/tor/torrc >/dev/null 2>&1
rm /etc/tor/torrc >/dev/null 2>&1
touch /etc/tor/torrc >/dev/null 2>&1

if [[ -z "$file" || ! -f "$file" || -z "$kind" || ! "$bin" || -z "$bin" ]]; then
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} Use: ${GREEN}onionbox --set-bridges </path/to/your_bridges_file> <bridges_kind> </path/to/your/proxy/bin>${NC}"
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} EXAMPLE: ${GREEN}onionbox -b my_bridges.txt obfs4 /usr/bin/obfs4proxy${NC}"
    echo -e "\n${BLUE}[${GREEN}!${BLUE}]${GREEN} Ensure this file contains ONLY the bridges and that it follows the correct format, Ex file: ${YELLOW}<${NC}Prefix: ${YELLOW}'bridge'> <${NC}type${YELLOW}> [${NC}IP${YELLOW}]${GREEN}:${YELLOW}[${NC}PORT${YELLOW}] [${NC}fingerprint${YELLOW}] [${NC}Key=value${YELLOW}]${NC}"
    echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} You see this message because something failed ${RED}(You forget to give some params !!)${NC}"
    exit 1
fi

bridges=$(cat "$file")

echo -e "\n# <--- Generated by TheOnionBox ---> #\n# This configuration File uses your bridges !!!#\n# This file cant be overwrited (has chattr +i), to unlock it run 'chattr -i /etc/tor/torrc'\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nMaxCircuitDirtiness 20 \nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nDNSPort 127.0.0.1:5353\nControlPort 127.0.0.1:9151\nSocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1\n" | tee /etc/tor/torrc >/dev/null 2>&1

chattr +i /etc/tor/torrc >/dev/null 2>&1

if tor --verify-config >/dev/null 2>&1; then
   echo -e "\n${P}[${GREEN}INFO${P}]${NC} Seems like your bridges are okay, try ${GREEN}'onionbox start/restart(if a current instance of the script is running)'${NC}"
   chown -R $TOR_USER:$TOR_USER /etc/tor/torrc
   chown -R $TOR_USER:$TOR_USER /var/lib/tor
   exit 0
else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} That config is not valid !!.. Run 'cat /etc/tor/torrc' to check it, or give a valid configuration file instead of making me waste time !${NC}"
   exit 1
fi

shift
break

;;

--reset-config|-reset-config|reset-config)
mode=10
   if [ $EUID -ne 0 ]; then
        echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} You must be root${NC}"
        exit 1
   fi

   echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${GREEN} Reseting Tor's configuration file to TheOnionBox default's${NC}"
   chattr -i /etc/tor/torrc >/dev/null 2>&1
   rm /etc/tor/torrc >/dev/null 2>&1
   touch /etc/tor/torrc >/dev/null 2>&1
   cat << 'EOT' > /etc/tor/torrc
# <--- Generated by TheOnionBox ---> #
# This configuration File uses default's template(Provided by tool) #
# Note: if you reading this and want to use with a browser, you would likely have to manually touch the proxy configuration and set the address/ports below to avoid features that are capable to break your anonimity !!
# This file cant be overwrited (has chattr +i), to unlock it run 'chattr -i /etc/tor/torrc'  

CookieAuthentication 0
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
AutomapHostsSuffixes .exit,.onion
TransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
SocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
DNSPort 127.0.0.1:5353
ControlPort 127.0.0.1:9151
EntryNodes {is},{ch},{fi},{ro}
ExitNodes {is},{ch},{fi},{ro}
StrictNodes 1
MaxCircuitDirtiness 5
ClientUseIPv6 0
ClientPreferIPv6ORPORT 0
ClientRejectInternalAddresses 1

EOT

chattr +i /etc/tor/torrc

echo -e "\n${P}[${GREEN}STATUS${P}]${GREEN} Done${NC}"

shift
break
;;

--restart|-restart|restart)
mode=11
if [ $EUID -ne 0 ]; then
    echo -e "\n${RED}[${NC}ERR${RED}]${GREEN} Please, Run as root${NC}"
    exit 1
fi

echo -e "\n${BLUE}[${GREEN}WARN${BLUE}]${P} TheOnionBox is Restarting..${NC}"

pkill -9 tor >/dev/null 2>&1
pkill -9 tor >/dev/null 2>&1
pkill -f tor >/dev/null 2>&1
pkill -f tor >/dev/null 2>&1

config

shift
break
;;

--help|-help|help|-h)

mode=13

help

shift

break

;;


--link|link|-l)

mode=14

link=$2

if [ -z "$link" ]; then
  echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Missing a destination address${NC}"
  exit 1
fi

if pgrep tor >/dev/null 2>&1 || ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then

echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} Trying to resolv ${YELLOW}"$link"${GREEN}...${NC}"
curl --socks5-hostname 127.0.0.1:9150 "$link" && echo -e "\n${BLUE}[${GREEN}STATUS${BLUE}]${YELLOW} "$link" ${GREEN}resolved !${NC}" || echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} An error ocurred while trying to resolv: $link${NC}" | exit 1
exit 0

else
   echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} TheOnionBox is not even running...${NC}"
   exit 1
fi

shift
break
;;

--show-config|-show-config|-sc)
mode=15

if [ -f /etc/tor/torrc ] && [ -f /etc/resolv.conf ]; then
    echo -e "\n${P}[${GREEN}INFO${P}]${GREEN} Tor config: ${GREEN}"
    cat /etc/tor/torrc
    echo -e "\n${BLUE}[${GREEN}INFO${BLUE}]${GREEN} DNS config: ${GREEN}"
    cat /etc/resolv.conf
else
  echo -e "\n${RED}[${GREEN}ERR${RED}]${GREEN} Configuration files were not found !!!, ${YELLOW}(/etc/tor/torrc, /etc/resolv.conf)${NC}"
  exit 1
fi

echo -e "\n${NC}"

shift
break
;;

--fast-shell|-fast-shell|fast-shell)
mode=true

osh

shift
break
;;

--*|-*|*)
mode=14

echo -e "\n${RED}[${NC}!${RED}]${GREEN} Unknown action: ${YELLOW}'$1'${GREEN}, see ${GREEN}'onionbox --help'${GREEN}, for detailed info${NC}"

exit 1

shift
break
;;

esac
done

# This dumb condition that throws a Help page

if [[ -z "$mode" ]]; then
    help
    echo -e "\n${RED}[${NC}ERR${RED}]${GREEN} TheOnionBox needs an argument !!${NC}"
    exit 1
fi
